import {QaExecution} from '../components/QaExecution';
import {useEffect, useRef, useState} from 'react';
import {apiFetch,jsonRequest} from '../http';
import {FindingsList} from '../components/FindingsList';
import {DownloadButton} from '../components/DownloadButton';
import {ExpandablePreview} from '../components/ExpandablePreview';
import type {Generation} from '../types';

type VisualPlan={kind:'text_only'|'diagram'|'chart'|'plot'|'equation'|'table'|'source_figure';description:string;reason:string};
const visualLabels:Record<VisualPlan['kind'],string>={text_only:'Text only',diagram:'Process or comparison diagram',chart:'Data chart',plot:'Function or data plot',equation:'Equation',table:'Table',source_figure:'Source PDF page'};
type OutlineSlide={visual?:VisualPlan|null;kind?:'opening'|'content'|'closing';id:string;title:string;points:string[];source_pages:number[]};
type Outline={title:string;rationale:string;slides:OutlineSlide[]};
type Series={name:string;values:number[]};
type Content={id:string;title:string;bullets:string[];notes:string;equation:string|null;
  diagram?:null|{kind:'process'|'comparison';nodes:{label:string;detail:string}[]};
  table?:null|{headers:string[];rows:string[][]};
  chart:null|{kind:string;categories:string[];series:Series[];x_label:string;y_label:string};
  plot:null|{kind:string;functions:string[];x_min:number;x_max:number;x:number[];y:number[];matrix:number[][];x_label:string;y_label:string;log_x:boolean;log_y:boolean};
  figure_page:number|null;citations:{page:number;quote:string}[];assumptions:string[]};
type Job={id:string;request:{topic:string;audience:string;length_preference:string;source:string};outline:Outline|null;revision:number;
  content_revision:number;approved_hash:string|null;deck:{slides:Content[]}|null;status:string;error:string|null;
  pages:{page:number;text:string;uncertainty:string}[];generation:Generation|null;progress:Record<string,string|number|null>;expires_at:number};

export function Creation({onHome}:{onHome:()=>void}){
  const [job,setJob]=useState<Job|null>(null), [outline,setOutline]=useState<Outline|null>(null);
  const [topic,setTopic]=useState(''),[audience,setAudience]=useState(''),[length,setLength]=useState('auto'),[source,setSource]=useState('topic');
  const [file,setFile]=useState<File|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[current,setCurrent]=useState(0);
  const [ack,setAck]=useState(false),[edit,setEdit]=useState<Content|null>(null),[dirty,setDirty]=useState(false);
  const epoch=useRef(0); const closed=useRef(new Set<string>());
  function accept(j:Job){if(closed.current.has(j.id))return;setJob(j);setOutline(j.outline);setDirty(false);setEdit(null);}
  useEffect(()=>{const id=new URLSearchParams(location.search).get('job');if(id)jsonRequest<Job>(`/api/jobs/${id}`).then(accept).catch(e=>setError(e.message));},[]);
  useEffect(()=>{if(!busy||!job)return;let live=true;const t=setInterval(()=>{jsonRequest<Job>(`/api/jobs/${job.id}`).then(j=>{if(live)setJob(prev=>prev?{...prev,progress:j.generation?.progress||j.progress}:prev);}).catch(()=>{});},1500);return()=>{live=false;clearInterval(t);};},[busy,job?.id]);
  async function perform(fn:()=>Promise<void>){const e=epoch.current;setBusy(true);setError('');try{await fn();}catch(err){if(epoch.current===e)setError((err as Error).message);}finally{if(epoch.current===e)setBusy(false);}}
  async function start(e:React.FormEvent){e.preventDefault();await perform(async()=>{
    const j=await jsonRequest<Job>('/api/jobs',{topic,audience,length_preference:length,source});accept(j);history.replaceState({},'',`?job=${j.id}`);
    if(source==='pdf'){if(!file)throw new Error('Choose a PDF.');const data=new FormData();data.append('file',file);const r=await apiFetch(`/api/jobs/${j.id}/pdf`,{method:'POST',body:data});const v=await r.json();if(!r.ok)throw new Error(v.detail);accept(v);}
    accept(await jsonRequest<Job>(`/api/jobs/${j.id}/outline/plan`,{}));
  });}
  async function close(){if(!job){onHome();return;}const result=await jsonRequest<{deleted:boolean}>(`/api/jobs/${job.id}/cancel`,{});closed.current.add(job.id);epoch.current++;setJob(null);setOutline(null);history.replaceState({},'',location.pathname);setBusy(false);if(!result.deleted){setError('Access revoked. Deletion is pending until the current operation releases its files.');}else onHome();}
  function updateSlide(i:number,changes:Partial<OutlineSlide>){if(!outline)return;setOutline({...outline,slides:outline.slides.map((s,n)=>n===i?{...s,...changes}:s)});setDirty(true);}
  function move(i:number,delta:number){if(!outline)return;const list=[...outline.slides];[list[i],list[i+delta]]=[list[i+delta],list[i]];setOutline({...outline,slides:list});setDirty(true);}
  async function approveOutline(){if(!job||!outline)return;await perform(async()=>{let j=job;if(dirty)j=await jsonRequest<Job>(`/api/jobs/${j.id}/outline`,{revision:j.revision,outline},'PUT');accept(await jsonRequest<Job>(`/api/jobs/${j.id}/outline/approve`,{revision:j.revision,acknowledge_uncertainty:ack}));});}
  async function generate(){if(!job)return;const e=epoch.current;await perform(async()=>{const j=await jsonRequest<Job>(`/api/jobs/${job.id}/generate`,{});if(e===epoch.current){accept(j);setCurrent(0);}});}
  const generation=job?.generation;
  const outlineApproved=Boolean(job?.approved_hash)&&!dirty;
  const resolved=new Set(generation?.human_decisions.filter(d=>d.output_slide==null).flatMap(d=>d.finding_ids)||[]);
  const findings=generation?.findings.filter(f=>f.output_slide===current||f.affected_slides?.includes(current))||[];
  const deckFindings=generation?.findings.filter(f=>f.output_slide===undefined&&!(f.affected_slides?.length))||[];
  async function approveFindings(ids:string[],rationale:string,slide?:number){if(!job||!generation)return false;let ok=false;await perform(async()=>{accept(await jsonRequest<Job>(`/api/jobs/${job.id}/decisions`,{generation_id:generation.generation_id,candidate_sha256:generation.candidate_sha256,finding_ids:ids,rationale,...(slide!=null?{output_slide:slide}:{})}));ok=true;});return ok;}
  async function download(format: 'pptx' | 'pdf'){if(!job||!generation)return;await perform(async()=>{const r=await apiFetch(`/api/jobs/${job.id}/download?generation_id=${generation.generation_id}&format=${format}`);if(!r.ok)throw new Error((await r.json()).detail);const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download=`Stevens-verified.${format}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);await close();});}
  async function saveContent(){if(!job?.deck||!edit)return;await perform(async()=>{const deck={slides:job.deck!.slides.map((s,i)=>i===current?edit:s)};accept(await jsonRequest<Job>(`/api/jobs/${job.id}/content`,{revision:job.content_revision,deck},'PUT'));});}
  return <main className="mx-auto max-w-6xl p-6"><div className="flex items-center justify-between gap-4"><h1 className="text-2xl font-bold">Generate a new presentation</h1><button className="btn-ghost" onClick={()=>close().catch(e=>setError(e.message))}>{job?'Cancel and delete':'Back'}</button></div>
    {error&&<p role="alert" className="my-4 rounded border border-red-300 bg-red-50 p-3 text-red-800">{error}</p>}
    {busy&&<p role="status" className="my-4 rounded bg-blue-50 p-3">{String(job?.progress.stage||'Working').replace(/_/g,' ')}{job?.progress.slide?` · slide ${job.progress.slide} of ${job.progress.total}`:''}{job?.progress.reviewed_slides?` · reviewed ${job.progress.reviewed_slides} of ${job.progress.total_slides} slides`:''}</p>}
    {!job&&<form onSubmit={start} className="card mt-6 space-y-5 p-6"><fieldset disabled={busy} className="space-y-5"><label className="block">Start from<select className="ml-4 rounded border p-2" value={source} onChange={e=>setSource(e.target.value)}><option value="topic">Topic or outline</option><option value="pdf">PDF document</option></select></label>
      {source==='pdf'&&<label className="block">Source PDF<input className="mt-2 block" type="file" accept="application/pdf,.pdf" required onChange={e=>setFile(e.target.files?.[0]||null)}/></label>}
      <label className="block">{source==='pdf'?'Focus or additional instructions (optional)':'Topic or starting outline'}<textarea className="mt-2 w-full rounded border p-3" rows={5} required={source==='topic'} value={topic} onChange={e=>setTopic(e.target.value)}/></label>
      <label className="block">Audience<input className="mt-2 w-full rounded border p-3" placeholder="For example, first-year engineering students" required value={audience} onChange={e=>setAudience(e.target.value)}/></label>
      <label className="block">Presentation length<select className="ml-4 rounded border p-2" value={length} onChange={e=>setLength(e.target.value)}><option value="auto">Auto — recommended</option><option value="brief">Brief — key takeaways</option><option value="standard">Standard — supporting explanation</option><option value="detailed">Detailed — evidence and examples</option></select></label>
      <p className="text-sm text-stevens-gray">The planner chooses a slide count to fit the material. You can edit the outline before generation. The outline includes a visual decision for each slide: diagrams, charts, plots, equations, tables, source PDF pages, or text only. Opening and closing use the Stevens template artwork.</p><button className="btn-red">Plan my presentation</button></fieldset></form>}
    {job&&!outline&&!busy&&job.request.source==='pdf'&&<label className="mt-5 block">Replace source PDF<input type="file" accept=".pdf" onChange={e=>{const chosen=e.target.files?.[0];if(!chosen)return;perform(async()=>{const data=new FormData();data.append('file',chosen);const response=await apiFetch(`/api/jobs/${job.id}/pdf`,{method:'POST',body:data});const value=await response.json();if(!response.ok)throw new Error(value.detail);accept(value);});}}/></label>}
    {job&&!outline&&!busy&&<button className="btn-red mt-5" onClick={()=>perform(async()=>accept(await jsonRequest<Job>(`/api/jobs/${job.id}/outline/plan`,{})))}>Retry outline planning</button>}
    {job&&outline&&!generation&&<section className="card mt-6 p-6"><h2 className="text-xl font-bold">1. Review and approve the outline · {outline.slides.length} slides</h2><p className="mt-2 text-sm">{outline.rationale}</p>
      {job.pages.some(p=>p.uncertainty)&&<div className="my-4 rounded bg-amber-50 p-3"><h3 className="font-bold">Source extraction needs review</h3>{job.pages.filter(p=>p.uncertainty).map(p=><p key={p.page}>Page {p.page}: {p.uncertainty}</p>)}<label><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/> I reviewed these source uncertainties.</label></div>}
      <fieldset disabled={busy} className="mt-5 space-y-4">{outline.slides.map((s,i)=><article key={s.id} className="rounded border p-4"><div className="flex gap-3"><span className="pt-2 font-bold">{i+1}{s.kind&&s.kind!=='content'&&<small className="block font-normal capitalize">{s.kind}</small>}</span><input aria-label={`Slide ${i+1} title`} className="min-w-0 flex-1 rounded border p-2 font-bold" value={s.title} onChange={e=>updateSlide(i,{title:e.target.value})}/><button className="btn-ghost" aria-label={`Move slide ${i+1} up`} disabled={i<=1||s.kind==='closing'} onClick={()=>move(i,-1)}>↑</button><button className="btn-ghost" aria-label={`Move slide ${i+1} down`} disabled={i>=outline.slides.length-2||s.kind==='opening'} onClick={()=>move(i,1)}>↓</button><button className="btn-ghost" disabled={s.kind==='opening'||s.kind==='closing'} onClick={()=>{setOutline({...outline,slides:outline.slides.filter((_,n)=>n!==i)});setDirty(true);}}>Remove</button></div>
        <textarea aria-label={`Slide ${i+1} key points`} className="mt-3 w-full rounded border p-2" rows={3} value={s.points.join('\n')} onChange={e=>updateSlide(i,{points:e.target.value.split('\n')})}/>{s.source_pages.length>0&&<p className="text-sm">Source pages: {s.source_pages.join(', ')}</p>}<div className="mt-3 space-y-2"><label className="block text-sm">Visual plan<select aria-label={`Slide ${i+1} visual plan`} className="ml-3 rounded border p-2" disabled={s.kind==='opening'||s.kind==='closing'} value={s.visual?.kind||'text_only'} onChange={e=>updateSlide(i,{visual:{kind:e.target.value as VisualPlan['kind'],description:s.visual?.description||'Use the key points above.',reason:'Selected during outline review.'},source_pages:e.target.value==='source_figure'&&!s.source_pages.length?job.pages.slice(0,1).map(p=>p.page):s.source_pages})}>{Object.entries(visualLabels).filter(([kind])=>kind!=='source_figure'||job.pages.length>0).map(([kind,label])=><option key={kind} value={kind}>{label}</option>)}</select></label>
          {s.visual&&<><label className="block text-sm">What to show<input aria-label={`Slide ${i+1} visual description`} className="mt-1 w-full rounded border p-2" value={s.visual.description} onChange={e=>updateSlide(i,{visual:{...s.visual!,description:e.target.value}})}/></label><p className="text-sm text-stevens-gray">{s.visual.reason}</p></>}
          {(s.kind==='opening'||s.kind==='closing')&&<p className="text-sm text-stevens-gray">Uses the approved Stevens {s.kind==='opening'?'mostly red opening':'statue-photo Thank you closing'} artwork.</p>}</div></article>)}
        <button className="btn-ghost" disabled={outline.slides.length>=30} onClick={()=>{setOutline({...outline,slides:[...outline.slides.slice(0,-1),{kind:'content',visual:{kind:'text_only',description:'Use the key point.',reason:'New slide; choose a visual if it helps.'},id:crypto.randomUUID(),title:'New slide',points:['Key point'],source_pages:[]},...outline.slides.slice(-1)]});setDirty(true);}}>Add slide</button>
        <p id="outline-next-step" role="status" className="rounded bg-blue-50 p-3">{outlineApproved?'Outline approved. Step 2 is ready: generate your slides and run mandatory QA.':dirty?'Your outline has changes. Approve this version to enable step 2.':'First, review the opening, content, and closing slides above. Approve the outline to enable step 2.'}</p>
        <div className="flex flex-wrap gap-3"><button className={outlineApproved?'btn-ghost':'btn-red'} disabled={outlineApproved} onClick={approveOutline}>{outlineApproved?'✓ Outline approved':'1. Save and approve outline'}</button><button className="btn-red" aria-describedby="outline-next-step" disabled={!outlineApproved} onClick={generate}>2. Generate and verify</button></div></fieldset>
    </section>}
    {job&&generation&&<div className="mt-6 grid gap-5 lg:grid-cols-[1fr_300px]"><section id="creation-review" tabIndex={-1} className="card p-5"><nav className="mb-4 flex items-center justify-between"><button className="btn-ghost" disabled={current===0||busy} onClick={()=>{setCurrent(current-1);setEdit(null);}}>Previous slide</button><span>Slide {current+1} of {job.deck?.slides.length||generation.built_slides}</span><button className="btn-ghost" disabled={current>=(job.deck?.slides.length||generation.built_slides)-1||busy} onClick={()=>{setCurrent(current+1);setEdit(null);}}>Next slide</button></nav>
      <ExpandablePreview alt={`Output slide ${current+1}`} className="w-full rounded border" src={`/api/jobs/${job.id}/preview/${current}?generation_id=${generation.generation_id}`}/>
      <h2 className="mt-5 font-bold">Findings for this slide</h2><FindingsList key={`${generation.generation_id}:${generation.candidate_sha256}:${current}`} findings={findings} currentSlide={current} decisions={generation.human_decisions} slideTargets={f=>f.affected_slides?.length?f.affected_slides:f.output_slide!=null?[f.output_slide]:[]} onNavigate={slide=>{setCurrent(slide);setEdit(null);document.getElementById('creation-review')?.scrollIntoView?.({behavior:'smooth'});}} resolved={resolved} busy={busy} onApprove={approveFindings}/>
      {job.deck?.slides[current]?.citations.map((c,i)=><details className="mt-3" key={i}><summary>Source PDF page {c.page}</summary><p>{c.quote}</p><img alt={`Source page ${c.page}`} className="mt-2 max-h-96" src={`/api/jobs/${job.id}/source/${c.page}`}/></details>)}
      {job.deck&&<button className="btn-ghost mt-4" disabled={busy} onClick={()=>setEdit(structuredClone(job.deck!.slides[current]))}>Edit slide content, chart, or formula</button>}
      {edit&&<fieldset disabled={busy} className="mt-4 space-y-3 rounded border p-4"><h3 className="font-bold">Edit {edit.title}</h3><label className="block">Bullet points<textarea className="w-full rounded border p-2" rows={4} value={edit.bullets.join('\n')} onChange={e=>setEdit({...edit,bullets:e.target.value.split('\n')})}/></label>
        <label className="block">Speaker notes<textarea className="w-full rounded border p-2" value={edit.notes} onChange={e=>setEdit({...edit,notes:e.target.value})}/></label>
        <label className="block">Visual<select className="ml-3 border p-2" value={edit.diagram?'diagram':edit.equation!==null?'math':edit.plot?'plot':edit.chart?'chart':edit.figure_page?'source':edit.table?'table':'none'} onChange={e=>{const v=e.target.value;setEdit({...edit,diagram:v==='diagram'?{kind:'process',nodes:[{label:'First step',detail:''},{label:'Next step',detail:''}]}:null,equation:v==='math'?'y = \\sin(x)':null,plot:v==='plot'?{kind:'function',functions:['sin(x)'],x_min:-5,x_max:5,x:[],y:[],matrix:[],x_label:'x',y_label:'y',log_x:false,log_y:false}:null,chart:v==='chart'?{kind:'column',categories:['A','B'],series:[{name:'Illustrative values',values:[1,2]}],x_label:'',y_label:''}:null,figure_page:v==='source'?1:null,table:v==='table'?{headers:['Category','Value'],rows:[['A','2']]}:null});}}><option value="none">Text only</option><option value="diagram">Process or comparison diagram</option><option value="math">Equation</option><option value="plot">Function plot</option><option value="chart">Editable chart</option><option value="table">Editable table</option>{job.pages.length>0&&<option value="source">Source PDF page</option>}</select></label>
        {edit.diagram&&<><label>Diagram type<select className="ml-3 border p-2" value={edit.diagram.kind} onChange={e=>setEdit({...edit,diagram:{...edit.diagram!,kind:e.target.value as 'process'|'comparison'}})}><option value="process">Process</option><option value="comparison">Comparison</option></select></label><label className="block">Steps or alternatives (2–6 lines, label | detail)<textarea className="w-full rounded border p-2" rows={4} value={edit.diagram.nodes.map(n=>`${n.label} | ${n.detail}`).join('\n')} onChange={e=>setEdit({...edit,diagram:{...edit.diagram!,nodes:e.target.value.split('\n').map(line=>{const [label,...detail]=line.split('|');return {label:label.trim(),detail:detail.join('|').trim()};})}})}/></label></>}
        {edit.equation!==null&&<label className="block">Equation (LaTeX math, no dollar signs)<input className="w-full border p-2" value={edit.equation} onChange={e=>setEdit({...edit,equation:e.target.value})}/></label>}
        {edit.plot&&<><label className="block">Functions (one per line)<textarea className="w-full border p-2" value={edit.plot.functions.join('\n')} onChange={e=>setEdit({...edit,plot:{...edit.plot!,kind:'function',functions:e.target.value.split('\n')}})}/></label><label>Minimum x <input type="number" className="w-24 border p-2" value={edit.plot.x_min} onChange={e=>setEdit({...edit,plot:{...edit.plot!,x_min:Number(e.target.value)}})}/></label><label> Maximum x <input type="number" className="w-24 border p-2" value={edit.plot.x_max} onChange={e=>setEdit({...edit,plot:{...edit.plot!,x_max:Number(e.target.value)}})}/></label></>}
        {edit.chart&&<><label className="block">Categories (comma separated)<input className="w-full border p-2" value={edit.chart.categories.join(',')} onChange={e=>setEdit({...edit,chart:{...edit.chart!,categories:e.target.value.split(',')}})}/></label>{edit.chart.series.map((s,i)=><div key={i}><label>{s.name} values<input className="w-full border p-2" value={s.values.join(',')} onChange={e=>setEdit({...edit,chart:{...edit.chart!,series:edit.chart!.series.map((a,n)=>n===i?{...a,values:e.target.value.split(',').map(Number)}:a)}})}/></label></div>)}</>}
        {edit.table&&<label className="block">Table (tab-separated cells; first row contains headers)<textarea className="w-full border p-2" rows={6} value={[edit.table.headers,...edit.table.rows].map(row=>row.join('\t')).join('\n')} onChange={e=>{const rows=e.target.value.split('\n').map(row=>row.split('\t'));setEdit({...edit,table:{headers:rows[0],rows:rows.slice(1)}});}}/></label>}
        {edit.figure_page&&<label>PDF page <input type="number" value={edit.figure_page} min={1} max={job.pages.length} onChange={e=>setEdit({...edit,figure_page:Number(e.target.value)})}/></label>}
        <p className="text-sm">Saving creates a new candidate and reruns all checks. Previous approvals do not carry over.</p><button className="btn-red" onClick={saveContent}>Save content and verify again</button></fieldset>}
    </section><aside className="card p-5"><h2 className="font-bold">Verification</h2>{generation&&<QaExecution generation={generation}/>}<p className="mt-3 font-semibold">{generation.state.replace(/_/g,' ')}</p><ul className="my-4 space-y-2 text-sm">{Object.entries(generation.checks).map(([k,v])=><li key={k}>{k.replace(/_/g,' ')}: <b>{v.status.replace(/_/g,' ')}</b></li>)}</ul>
      <DownloadButton disabled={busy||!generation.download_allowed} pdfAvailable={!!generation.pdf_available} onDownload={download}/><p className="mt-2 text-sm">QA must complete. Resolve each material issue or accept it after human review.</p>
      <button className="btn-ghost mt-3 w-full" disabled={busy} onClick={generate}>Regenerate and verify</button><button className="btn-ghost mt-3 w-full" disabled={busy} onClick={()=>{setJob({...job,generation:null});setOutline(job.outline);setDirty(true);}}>Revise outline</button>
      <p className="mt-4 text-xs">Processing files expire by {new Date(job.expires_at*1000).toLocaleTimeString()}. Download and finish ends editing and deletes files. Unsupported claims need review; automated QA is not a guarantee of factual truth.</p>
      {deckFindings.length>0&&<details className="mt-5" open><summary>Deck-wide findings ({deckFindings.length})</summary><FindingsList findings={deckFindings} resolved={resolved} busy={busy} onApprove={approveFindings} deckWide/></details>}
    </aside></div>}
  </main>;
}
